### Kasus 1
#### Tabel Kebenaran OR

In [5]:
# Import necessary libraries
import numpy as np

#Adaline neural network
def Adaline(Input, Target, lr=0.2, stop=0.001):
	weight = np.random.random(Input.shape[1])
	bias = np.random.random(1)
	
	Error=[stop +1]
	# check the stop condition for the network
	while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
		error = []
		for i in range(Input.shape[0]):
			Y_input = sum(weight*Input[i]) + bias
			
			# Update the weight
			for j in range(Input.shape[1]):
				weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]

			# Update the bias
			bias=bias + lr*(Target[i]-Y_input)
			
			# Store squared error value
			error.append((Target[i]-Y_input)**2)
		# Store sum of square errors
		Error.append(sum(error))
		print('Error :',Error[-1])
	return weight, bias

# Input dataset
x = np.array([[1.0, 1.0, 1.0],
			[1.0, -1.0, 1.0],
			[-1.0, 1.0, 1.0],
			[-1.0, -1.0, -1.0]])
# Target values
t = np.array([1, 1, 1, -1])

w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)

Error : [1.22425402]
Error : [0.84781546]
Error : [0.59660288]
Error : [0.41331808]
Error : [0.28606925]
Error : [0.19798581]
Error : [0.13702366]
Error : [0.09483245]
Error : [0.06563242]
Error : [0.04542342]
Error : [0.03143701]
Error : [0.02175718]
Error : [0.01505789]
Error : [0.01042139]
Error : [0.00721252]
Error : [0.0049917]
Error : [0.0034547]
Error : [0.00239095]
Error : [0.00165475]
Error : [0.00114523]
Error : [0.0007926]
weight : [0.00974753 0.00974753 0.98806176]
Bias : [0.00974753]


In [6]:
# Predict from the evaluated weight and bias of adaline
def prediction(X,w,b):
	y=[]
	for i in range(X.shape[0]):
		x = X[i]
		y.append(sum(w*x)+b)
	return y
prediction(x,w,b)

[array([1.01730435]),
 array([0.99780929]),
 array([0.99780929]),
 array([-0.99780929])]

### Kasus 2
#### Tabel Kebenaran AND

In [7]:
# Import necessary libraries
import numpy as np

#Adaline neural network
def Adaline(Input, Target, lr=0.1, stop=0.05):
	weight = np.random.random(Input.shape[1])
	bias = np.random.random(1)
	
	Error=[stop +1]
	# check the stop condition for the network
	while Error[-1] > stop or Error[-1]-Error[-2] > 0.005:
		error = []
		for i in range(Input.shape[0]):
			Y_input = sum(weight*Input[i]) + bias
			
			# Update the weight
			for j in range(Input.shape[1]):
				weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]

			# Update the bias
			bias=bias + lr*(Target[i]-Y_input)
			
			# Store squared error value
			error.append((Target[i]-Y_input)**2)
		# Store sum of square errors
		Error.append(sum(error))
		print('Error :',Error[-1])
	return weight, bias

# Input dataset
x = np.array([[1.0, 1.0, 1.0],
			[1.0, -1.0, -1.0],
			[-1.0, 1.0, -1.0],
			[-1.0, -1.0, -1.0]])
# Target values
t = np.array([1, -1, -1, -1])

w,b = Adaline(x, t, lr=0.1, stop=0.05)
print('weight :',w)
print('Bias :',b)

Error : [3.8940758]
Error : [1.40078049]
Error : [0.65761056]
Error : [0.39364482]
Error : [0.28226031]
Error : [0.22497528]
Error : [0.18890092]
Error : [0.16234367]
Error : [0.14091115]
Error : [0.12281634]
Error : [0.1072292]
Error : [0.09368673]
Error : [0.08187854]
Error : [0.07156727]
Error : [0.06255764]
Error : [0.05468335]
Error : [0.04780062]
weight : [0.08809003 0.08803398 0.82714425]
Bias : [-0.08791742]


In [8]:
# Predict from the evaluated weight and bias of adaline
def prediction(X,w,b):
	y=[]
	for i in range(X.shape[0]):
		x = X[i]
		y.append(sum(w*x)+b)
	return y
prediction(x,w,b)

[array([0.91535084]),
 array([-0.91500562]),
 array([-0.91511771]),
 array([-1.09118568])]