In [1]:
import numpy as np

# Definisikan pola untuk huruf X dan O dalam matriks 5x5
X_pattern = np.array([[1, 0, 0, 0, 1],
                      [0, 1, 0, 1, 0],
                      [0, 0, 1, 0, 0],
                      [0, 1, 0, 1, 0],
                      [1, 0, 0, 0, 1]])

O_pattern = np.array([[0, 1, 1, 1, 0],
                      [1, 0, 0, 0, 1],
                      [1, 0, 0, 0, 1],
                      [1, 0, 0, 0, 1],
                      [0, 1, 1, 1, 0]])

In [2]:
X_pattern

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [3]:
O_pattern

array([[0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0]])

In [4]:
# Hitung bobot sinaptik menggunakan aturan Hebb
def hebb_learning(patterns):
    num_patterns, pattern_size = patterns.shape
    weights = np.zeros((pattern_size, pattern_size))

    for pattern in patterns:
        weights += np.outer(pattern, pattern)
    
    # Normalisasi bobot agar dalam rentang -1 hingga 1
    weights /= pattern_size
    return weights

# Fungsi aktivasi menggunakan fungsi signum
def activation_function(x):
    return np.sign(x)

# Lakukan pembelajaran Hebb pada pola huruf X dan O
patterns = np.array([X_pattern.flatten(), O_pattern.flatten()])
weights = hebb_learning(patterns)

In [5]:
patterns

array([[1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 1, 0]])

In [6]:
weights

array([[0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04, 0.  , 0.04, 0.  , 0.  ,
        0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04, 0.  , 0.04, 0.  ,
        0.  , 0.  , 0.04],
       [0.  , 0.04, 0.04, 0.04, 0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.04,
        0.  , 0.  , 0.  , 0.04, 0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04,
        0.04, 0.04, 0.  ],
       [0.  , 0.04, 0.04, 0.04, 0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.04,
        0.  , 0.  , 0.  , 0.04, 0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04,
        0.04, 0.04, 0.  ],
       [0.  , 0.04, 0.04, 0.04, 0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.04,
        0.  , 0.  , 0.  , 0.04, 0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04,
        0.04, 0.04, 0.  ],
       [0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04, 0.  , 0.04, 0.  , 0.  ,
        0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.  , 0.04, 0.  , 0.04, 0.  ,
        0.  , 0.  , 0.04],
       [0.  , 0.04, 0.04, 0.04, 0.  , 0.04, 0.  , 0.  , 0.  , 0.04, 0.04,
        0.  , 0.  , 0.  , 0.04, 0.04, 0.  , 0.  , 0

In [7]:
# Fungsi untuk mengenali huruf berdasarkan bobot yang telah dipelajari
def recognize(input_pattern, weights):
    net_input = np.dot(input_pattern, weights)
    output = activation_function(net_input)
    return output

# Contoh pengenalan huruf X
test_X = np.array([[0, 1, 0, 1, 0],
                   [1, 0, 1, 0, 1],
                   [0, 1, 0, 1, 0],
                   [1, 0, 1, 0, 1],
                   [0, 1, 0, 1, 0]])

output_X = recognize(test_X.flatten(), weights)
print("Hasil pengenalan huruf X:", output_X)

# Contoh pengenalan huruf O
test_O = np.array([[0, 1, 1, 1, 0],
                   [1, 0, 0, 0, 1],
                   [1, 0, 0, 0, 1],
                   [1, 0, 0, 0, 1],
                   [0, 1, 1, 1, 0]])

output_O = recognize(test_O.flatten(), weights)
print("Hasil pengenalan huruf O:", output_O)

Hasil pengenalan huruf X: [0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.
 0.]
Hasil pengenalan huruf O: [0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.
 0.]
