In [1]:
from sklearn.linear_model import Perceptron
import numpy as np

### Kasus 1

Tabel Kebenaran AND dengan Input dan Output Bipolar.

In [22]:
# Data training
X = np.array([[1, 1],
              [1, -1],
              [-1, 1],
              [-1, -1]])
X

array([[ 1,  1],
       [ 1, -1],
       [-1,  1],
       [-1, -1]])

In [23]:
y = np.array([1, 1, 1, -1])
y

array([ 1,  1,  1, -1])

In [24]:
# Inisialisasi dan pelatihan model Perceptron
perceptron = Perceptron(max_iter=100, tol=None, eta0=1)
perceptron.fit(X, y)

# Prediksi
predictions = perceptron.predict(X)

# Menampilkan hasil
predictions

array([ 1,  1,  1, -1])

### Kasus 2

Pengenenalan Huruf X dan O.

In [25]:
# Definisikan pola huruf X dan O
X_pola = np.array([[1, -1, -1, -1, 1],
                      [-1, 1, -1, 1, -1],
                      [-1, -1, 1, -1, -1],
                      [-1, 1, -1, 1, -1],
                      [1, -1, -1, -1, 1]])

X_pola

array([[ 1, -1, -1, -1,  1],
       [-1,  1, -1,  1, -1],
       [-1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1],
       [ 1, -1, -1, -1,  1]])

In [26]:
O_pola = np.array([[-1, 1, 1, 1, -1],
                      [1, -1, -1, -1, 1],
                      [1, -1, -1, -1, 1],
                      [1, -1, -1, -1, 1],
                      [-1, 1, 1, 1, -1]])
O_pola

array([[-1,  1,  1,  1, -1],
       [ 1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [-1,  1,  1,  1, -1]])

In [27]:
# Bentuk data training dan label
X_train = np.vstack((X_pola.flatten(), O_pola.flatten()))
y_train = np.array([1, -1])  # 1 untuk X, -1 untuk O

In [28]:
X_train

array([[ 1, -1, -1, -1,  1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1, -1,
         1, -1,  1, -1,  1, -1, -1, -1,  1],
       [-1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1,
        -1, -1, -1,  1, -1,  1,  1,  1, -1]])

In [29]:
y_train

array([ 1, -1])

In [30]:
# Inisialisasi dan pelatihan model Perceptron
perceptron = Perceptron(max_iter=100, tol=None, random_state=0)
perceptron.fit(X_train, y_train)

# Prediksi
X_pred = perceptron.predict(X_train)

# Menampilkan hasil
print("Prediksi:", X_pred)

Prediksi: [ 1 -1]


### Kasus 3

Tabel Kebenaran OR dengan Input dan Output Bipolar.

In [31]:
# Data training
X = np.array([[1, 1],
              [1, -1],
              [-1, 1],
              [-1, -1]])
X

array([[ 1,  1],
       [ 1, -1],
       [-1,  1],
       [-1, -1]])

In [32]:
y = np.array([1, 1, 1, -1])
y

array([ 1,  1,  1, -1])

In [33]:
# Inisialisasi dan pelatihan model Perceptron
perceptron = Perceptron(max_iter=100, tol=None, eta0=1)
perceptron.fit(X, y)

# Prediksi
predictions = perceptron.predict(X)

# Menampilkan hasil
predictions

array([ 1,  1,  1, -1])